# This configuration should be fetched from Spring Cloud Config
# Common configuration across different environments

#Spring Service Registry
eureka:
  client:
    enabled: false

spring:
  jpa:
    open-in-view: false
  profiles:
    #default profile, this can be overriden by environmental variable
    active: local
